name: Keep API Alive

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: |
          curl -s -o /dev/null -w "%{http_code}" ${{ vars.API_URL }}
